// Lista de iconos disponibles de lucide-react
import * as LucideIcons from 'lucide-react'

// Lista completa de iconos de lucide-react (más comunes y útiles)
export const lucideIcons = [
  'tv',
  'book',
  'rat',
  'gift',
  'align-horizontal-justify-center',
  'wifi',
  'phone',
  'mail',
  'map-pin',
  'star',
  'heart',
  'shield',
  'zap',
  'trophy',
  'crown',
  'gem',
  'sparkles',
  'rocket',
  'globe',
  'home',
  'user',
  'users',
  'settings',
  'bell',
  'search',
  'menu',
  'x',
  'check',
  'plus',
  'minus',
  'edit',
  'trash',
  'save',
  'download',
  'upload',
  'share',
  'link',
  'image',
  'video',
  'music',
  'file',
  'folder',
  'calendar',
  'clock',
  'sun',
  'moon',
  'cloud',
  'rain',
  'snow',
  'play',
  'pause',
  'stop',
  'skip-forward',
  'skip-back',
  'volume',
  'volume-x',
  'headphones',
  'mic',
  'camera',
  'film',
  'monitor',
  'laptop',
  'smartphone',
  'tablet',
  'keyboard',
  'mouse',
  'hard-drive',
  'database',
  'server',
  'cloud-upload',
  'cloud-download',
  'lock',
  'unlock',
  'key',
  'eye',
  'eye-off',
  'filter',
  'sliders',
  'grid',
  'list',
  'layout',
  'columns',
  'rows',
  'package',
  'shopping-cart',
  'credit-card',
  'wallet',
  'dollar-sign',
  'euro',
  'pound-sterling',
  'yen',
  'bitcoin',
  'trending-up',
  'trending-down',
  'bar-chart',
  'line-chart',
  'pie-chart',
  'activity',
  'target',
  'flag',
  'award',
  'medal',
  'badge',
  'tag',
  'bookmark',
  'book-open',
  'graduation-cap',
  'school',
  'briefcase',
  'building',
  'store',
  'shopping-bag',
  'coffee',
  'utensils',
  'car',
  'bike',
  'plane',
  'train',
  'ship',
  'map',
  'navigation',
  'compass',
  'gps',
  'radio',
  'signal',
  'bluetooth',
  'wifi-off',
  'router',
  'cpu',
  'memory-stick',
  'usb',
  'plug',
  'battery',
  'battery-charging',
  'power',
  'lightbulb',
  'flame',
  'droplet',
  'wind',
  'thermometer',
  'umbrella',
  'tree',
  'flower',
  'leaf',
  'mountain',
  'waves',
  'fish',
  'dog',
  'cat',
  'bird',
  'bug',
  'spider',
  'gamepad',
  'dice',
  'puzzle',
  'palette',
  'brush',
  'pen',
  'pencil',
  'highlighter',
  'eraser',
  'scissors',
  'ruler',
  'calculator',
  'microscope',
  'telescope',
  'flask',
  'beaker',
  'atom',
  'rocket',
  'satellite',
  'planet',
] as const

export type LucideIconName = typeof lucideIcons[number]

// Función helper para obtener el componente de icono
export function getLucideIcon(iconName: string) {
  if (!iconName) return LucideIcons.Circle
  
  // Convertir el nombre del icono a PascalCase (ej: 'align-horizontal-justify-center' -> 'AlignHorizontalJustifyCenter')
  const pascalCase = iconName
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')
  
  const IconComponent = (LucideIcons as Record<string, any>)[pascalCase]
  return IconComponent || LucideIcons.Circle
}

